(*********************************************************************************)
(*  dunolint-actions - Reusable GitHub Actions for the dunolint linter tool      *)
(*  SPDX-FileCopyrightText: 2024-2025 Mathieu Barbin <mathieu.barbin@gmail.com>  *)
(*  SPDX-License-Identifier: MIT                                                 *)
(*********************************************************************************)

(* CR mbarbin: Next-steps

   - replace the output by an empty but valid config.
   - start adding some rules to validate the setup.

   Currently we have an invalid config ("Hello") so we can do one run and verify
   that the lint-check will exit with a non-zero code. *)

let () =
  print_endline ";; This file is generated by [main.ml]. Do not edit!";
  print_endline "Hello";
  ()
;;
