name: "lint-check"
description: "Run dunolint lint check on the project."
author: "dunolint contributors"
inputs:
  dunolint-config:
    description: "Path to the dunolint config file (resolved relative to the repository root, not the target directory)."
    required: false
    default: ""
  root:
    description: "Override the workspace root detection. This is the path to the workspace root where dunolint should be run."
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Run dunolint lint check
      shell: sh
      run: |
        "${{ github.action_path }}/lint-check.sh"
      env:
        DUNOLINT_CONFIG: ${{ inputs.dunolint-config }}
        DUNOLINT_ROOT: ${{ inputs.root }}
branding:
  icon: "check-circle"
  color: "green"
