name: OCaml CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**" # This will match pull requests targeting any branch

defaults:
  run:
    shell: bash

jobs:
  ocaml-build-test:
    strategy:
      matrix:
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Check build and tests
        # We review and manually update the action's commit used below.
        uses: mbarbin/setup-dune@ae2985bcdedc6fb24e5743d6f9dace9cf262b41c # v2.0.0+patch-4
        with:
          version: "3.21.0"
          directory: ./test
          cache-readonly: ${{ github.ref != 'refs/heads/main' }}
          steps: all
